---
- name: "<r_open_source_license_t_common> template a file to {{ project_path }}/LICENSE"
  template:
    src: "{{ license | lower }}.j2"
    dest: "{{ project_path }}/LICENSE"
    #owner:
    #group:
    #mode: "0644"
    #validate:
    #backup: yes
